version: 2.1

orbs:
  python: circleci/python@1.5.0
  docker: circleci/docker@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Linting
          command: flake8

  docker_deploy:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: deploy image to docker
          command: |
            docker build -t $DOCKER_USER/opc_13:$CIRCLE_SHA1 .
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker tag $DOCKER_USER/opc_13:$CIRCLE_SHA1 $DOCKER_USER/opc_13:release
            docker push $DOCKER_USER/opc_13:$CIRCLE_SHA1
            docker push $DOCKER_USER/opc_13:release

  heroku_deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: deploy docker image to heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a opc-13 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a opc-13 web

workflows:
  main:
    jobs:
      - build-and-test
      - docker_deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
      - heroku_deploy:
          requires:
            - docker_deploy
          filters:
            branches:
              only:
                - master
